version: '3.2'

services:

  substrate-interface-api:
    build: .
    image: substrate-interface-api
    ports:
      - '8000:8000'
    volumes:
      - '.:/usr/src/app'
    command: ./start.sh
    environment:
      - PYTHONPATH=/usr/src/app
      - ENVIRONMENT=dev
      - TYPE_REGISTRY=kusama
      - SUBSTRATE_ADDRESS_TYPE=2
      - SUBSTRATE_RPC_URL=http://54.219.167.140:9933/
    depends_on:
      - redis
  redis:
    image: redis:3.2.11

volumes:
  substrate-data:
